name: 'Build macOS'

on:
  workflow_dispatch:  # Manual trigger only
  push:              # Trigger on push to specific branch
    branches: [mac-build-v2]  

jobs:
  build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup macOS build environment
        run: buildscripts/ci/setup-macos.sh

      - name: Build all macOS variants
        #run: buildscripts/darwin-1.6.13/build-releaseonly.sh
        run: buildscripts/buildall-darwin.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hyperspace-macos-binaries
          path: |
            build-darwin-*/Hyperspace.*.dylib
