name: 'Release Linux & Windows'

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binaries
        run: buildscripts/ci/buildall-release-only-from-docker.sh

      - name: Package Linux
        run: buildscripts/ci/package-linux.sh ${{ steps.version.outputs.version }}

      - name: Package Windows
        run: buildscripts/ci/package-windows.sh ${{ steps.version.outputs.version }}

      - name: Upload Linux release
        uses: softprops/action-gh-release@v1
        with:
          files: FTL.Hyperspace.${{ steps.version.outputs.version }}-Linux.zip
          tag_name: v${{ steps.version.outputs.version }}

      - name: Upload Windows release
        uses: softprops/action-gh-release@v1
        with:
          files: FTL.Hyperspace.${{ steps.version.outputs.version }}-Windows.zip
          tag_name: v${{ steps.version.outputs.version }}
